export const OPEN_MODAL_WINDOW = 'OPEN_MODAL_WINDOW';
export const CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW';
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSES_WITH_SEARCH = 'GET_COURSES_WITH_SEARCH';
